### PR TITLE
Drop dependency on deprecated `gulp-util`

### LINKED ISSUE #54: Replace deprecated dependency gulp-util
[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been recently deprecated. Continuing to use this dependency may prevent the use of your library with the latest release of Gulp 4 so **it is important to replace `gulp-util`**.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

Your package is one of the most popular packages still relying on `gulp-util`, it would be good to publish a fixed version to npm as soon as possible.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

### PR DESCRIPTION
**Pull request by TheDancingCode**
Closes #54

### CODE REVIEW

**Comment by tracker1** [comment]
@TheDancingCode Would you like to be added to the contributors in the package.json?

@demurgos If you'd like, I could add you as a contributor so you can push to the project.

**Comment by demurgos** [comment]
I'll be upfront that being able to perform these sort of maintenance updates when there are some ecosystem-wide change would be good but I will most likely won't have time to deal with issues specific to this library.
It may be helpful occasionally so if it's fine with you, you can add me.

**Comment by tracker1** [comment]
demurgos, you've been added...  

after a merge...

```
npm version (patch|minor|major)
git push
git push --tags
``` 

travis should do the publish to npm... though it was a bit wonky yesterday.

**Comment by tracker1** [comment]
I'm frankly not even using gulp anymore, mostly webpack and/or npm scripts for a few years, so I get what you're saying.  I don't think there's really a need to add new features, most changes are because of API changes.

**Comment by demurgos** [comment]
Ok, thanks for the invite.

**Pull request merged**
