### PR TITLE
Added try catch to directory check

### PR DESCRIPTION
**Pull request by el-davo**
We need a quick fix for this as its breaking our builds - https://github.com/tracker1/gulp-header/issues/37

Added a dirty try catch. Can you let us know if this is ok

### CODE REVIEW

**Comment by don4of4** [comment]
Maybe do an interactive rebase to squash the commits.  Other than that looks fine to me.

**Comment by mryellow** [comment]
The degree of pretty in the commit history hardly matters when so many builds are broken.

**Comment by el-davo** [comment]
Agree with above. I dont have time to do this right now. Can you please merge this.

**Comment by don4of4** [comment]
@mryellow @el-davo Sorry for the confusion, I'm not an admin here.  If I was I would have squashed and merged myself.  _Frankly, it's ridiculous this issue is still active._

**Comment by don4of4** [comment]
@tracker1  Michael, you still with us?

**Comment by minwe** [comment]
Got `fs.lstatSync` error, too.

**Pull request merged**
