### PR TITLE
Fix support for file data (`gulp-data`)

### PR DESCRIPTION
**Pull request by demurgos**
Closes tracker1/gulp-header#56

### CODE REVIEW

**Comment by demurgos** [comment]
@tracker1 
I'll let you review / merge / publish.

**Comment by tracker1** [comment]
Sorry this slipped through the cracks on my end... travis should publish from the tag I just made.

**Comment by tracker1** [comment]
@demurgos would you be interested in being added as a collaborator?

All you'd need to do is accept the pull request, and run `npm run publish patch` (or minor, or major) in this repo after pulling the latest after a rebase/merge for PR.

**Comment by demurgos** [comment]
Okay. Thanks for the details.

I preferred for you to take a look at it. I'll submit changes myself next time.

**Comment by tracker1** [comment]
Totally understand... :-)

**Pull request merged**
