### PR TITLE
adds sourcemap support

### PR DESCRIPTION
**Pull request by madhums**
I followed the gulp-concat plugin and added support for sourcemaps.
I had to add [concat-with-sourcemaps](https://github.com/floridoo/concat-with-sourcemaps) as a dep.

Please review and let me know if anything has to be changed.

### CODE REVIEW

**Comment by KenPowers** [comment]
:+1:

**Comment by contra** [comment]
This is great but it won't work with other sourcemaps in the pipeline. Check out how gulp-concat does it - you need to use applySourceMaps

**Comment by tracker1** [comment]
@madhums I'd suggest following @contra's advice on this.. beyond that, it looks like the test are failing.  Please add/update the tests accordingly.

**Comment by madhums** [comment]
@contra thanks, I will do it tonight. @tracker1 some tests are failing in the newly released iojs 3.0.0. It works well in 2.5.x, but I will try to fix it.

**Comment by madhums** [comment]
@contra I added the Flush stream method where the sourcemapped content is pushed. I was thinking that [concat-with-sourcemaps](https://github.com/floridoo/concat-with-sourcemaps) would do the applySourceMaps stuff (as this is how it is done in gulp-concat). 

Let me know if this seems right. If not, should I use an ast parser and then applySourceMaps?

I tested the above in the following task, it seems to work fine.

```js
var header = require('gulp-header');

return gulp.src(files)
  .pipe(sourcemaps.init())
    .pipe(concat('app.js'))
    .pipe(header('window.locales = { en: {} }'))
    .pipe(gulpif(minify, uglify({ mangle: false })))
    .pipe(header(banner, { pkg: pkg }))
  .pipe(sourcemaps.write('./'))
  .pipe(gulp.dest(dist + '/'));
```

**Comment by contra** [comment]
Ah yeah, concat-with-sourcemaps does handle that - my bad. LGTM

**Comment by madhums** [comment]
Ok great! @tracker1 can you review the PR?

**Comment by tracker1** [comment]
LGTM...

**Comment by tracker1** [comment]
closes #7

**Comment by tracker1** [comment]
@madhums Thanks for your great work on this.

**Comment by madhums** [comment]
:+1:

**Pull request merged**
