### PR TITLE
Fix gulp-header with 0 or multiple files

### PR DESCRIPTION
**Pull request by jacobboland**
Fixes https://github.com/tracker1/gulp-header/issues/18 and https://github.com/tracker1/gulp-header/issues/17 with tests for each.

### CODE REVIEW

**Comment by whitneyit** [comment]
@jacobboland can you look at merging this with #11.

The main differences are here

```diff
-    var template = gutil.template(headerText, extend({file : file}, data));
+    var template = headerText;
+    if (data !== false) {
+      template = gutil.template(headerText, extend({file : file}, data));
+    }
+
```

This way you are not forced to provide a `data` Object.

That way I can close my PR

**Comment by jacobboland** [comment]
@whitneyit That would be up to @tracker1. This is fixing a change that broke our build.

**Comment by whitneyit** [comment]
Valid point. I'll wait :smile:

**Comment by madhums** [comment]
sorry for breaking this! I believe this also fixes #22 and other issues caused in the prev release @tracker1

**Comment by jacobboland** [comment]
No worries @madhums . Would you mind verifying that this branch still works for source maps?

**Comment by tracker1** [comment]
Merged and published... @madhums can you confirm that sourcemaps still works, and across multiple headers per #22 ?

Sorry, I just don't have time to do this right now.

**Comment by madhums** [comment]
yep! sourcemaps seems to be working fine!

**Comment by tracker1** [comment]
@madhums  Cool, thanks for confirming... It looks like all the open issues are closed/confirmed now.

**Comment by tracker1** [comment]
@whitneyit fyi, your requested change is now in place... passing an explicit false as the data parameter will disable template processing and inject the header as-is.

**Comment by whitneyit** [comment]
Awesome mate. Cheers

**Pull request merged**
